config/routes.rb
Rails.application.routes.draw do
  get 'bases/new'

  get 'sessions/new'

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン機能
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
 
  resources :users do
    member do
      get 'edit_basic_info'
      get 'edit_basic_info_admin'
      get 'working_list'
      patch 'update_basic_info'
      get 'attendance_log'
      get 'csv_export'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'

      get 'attendances/req_overtime'
      patch 'attendances/update_overtime'
      get 'attendances/notice_overtime'
      patch 'attendances/update_notice_overtime'
      get 'attendances/notice_change_at'
      patch 'attendances/update_notice_change_at'
      get 'reports/notice_report'
      patch 'reports/update_report'
    end
    collection {post :import}
    resources :attendances, only: :update
    resources :reports, only: :create
  end
  resources :bases do
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  has_many :reports, dependent: :destroy
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :affiliation, length: { in: 2..50 }, allow_blank: true
  validates :basic_work_time, presence: true
  validates :designated_work_start_time, presence: true
  validates :designated_work_end_time, presence: true
  validates :employee_number, presence: true, length: { maximum: 4 }
  validates :uid, presence: true, length: { maximum: 4 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end

  # importメソッド
  def self.import(file)
    @regist_result = false
    CSV.foreach(file.path, encoding: 'Shift_JIS:UTF-8', headers: true) do |row|
      # user = find_by(id: row["id"]) || new
      user = new

      # CSVからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updatable_attributes)
      if user.save
        @regist_result = true
      end
    end
    return true if @regist_result
    return false unless @regist_result
  end
  
  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "email", "affiliation", "employee_number", "uid", "basic_work_time", "designated_work_start_time", "designated_work_end_time", "superior", "admin", "password"]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info, :edit_basic_info_admin, :working_list, :attendance_log, :csv_export]
  # アクセス先のログインユーザーor上長（管理者も不可）
  before_action :admin_or_correct_user, only: :show
  # ログイン中のユーザーか
  before_action :logged_in_user, only: [:edit, :index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info, :edit_basic_info_admin, :attendance_log, :working_list]
  # アクセス先のログインユーザー
  before_action :correct_user, only: [:edit, :update, :attendance_log]
  # 管理者ユーザー
  before_action :admin_user, only: [:index, :destroy, :edit_basic_info, :update_basic_info, :edit_basic_info_admin, :working_list]
  # 1か月分の勤怠情報を取得
  before_action :set_one_month, only: [:show,  :attendance_log, :csv_export]

  def index
    @users = User.paginate(page: params[:page])
    @users = @users.where('name like ?', "%#{params[:search]}%") if params[:search].present?
  end
  
  def show
    @users = User.all
    @worked_sum = @attendances.where.not(started_at: nil).count
    @r_count = Report.where(r_request: @user.name, r_approval: "申請中").count
    @a_count = Attendance.where(c_request: @user.name, c_approval: "申請中").count
    @o_count = Attendance.where(o_request: @user.name, o_approval: "申請中").count
  
    # csv出力
    respond_to do |format|
      format.html 
        # html用の処理を記述
      format.csv do |csv|
        # csv用の処理を記述
        send_attendances_csv(@attendances)
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "アカウント情報を更新しました。"
      redirect_to edit_user_url
    else
      flash[:danger] = "#{@user.name}のアカウント情報の更新は失敗しました。"
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
  end

  def edit_basic_info_admin
  end
  
  def working_list
    @users = User.all
  end

  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br><li>" + @user.errors.full_messages.join("</li><li>")
    end
    redirect_to users_url
  end

  def import
    # fileはtmp(temporary)に自動保存
    if params[:file].presence
      @regist_check = User.import(params[:file])

      if @regist_check
        flash[:success] = "CSVファイルのインポートが完了しました。"
      else
        flash[:danger] = "更新可能なデータがありませんでした。"
      end
    else
      flash[:danger] = "CSVファイルを選択してください。"
    end
    redirect_to users_url
  end
  
  # 勤怠修正ログ
  def attendance_log
    @attendances = Attendance.where(user_id: @user).where(c_approval: "承認").order(worked_on: "DESC")

    if params[:attendance].present?
      unless params[:attendance][:worked_on] == ""
        @search_date = params[:attendance][:worked_on] + "-1"
        @attendances = @attendances.where(started_at: @search_date.in_time_zone.all_year)
                                    .where(started_at: @search_date.in_time_zone.all_month)
        if @attendances.count == 0
          flash.now[:warning] = "承認済みの修正履歴がありません。"
        end
      else
        flash.now[:warning] = "年月を選択してください。"
      end
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :affiliation, :employee_number, :uid, :password, :basic_work_time, :designated_work_start_time, :designated_work_end_time)
    end
    
    def basic_info_params
      params.require(:user).permit(:name, :email, :affiliation, :employee_number, :uid, :password, :basic_work_time, :designated_work_start_time, :designated_work_end_time)
    end

    def send_attendances_csv(attendances)
      #文字化け防止
      bom = "\uFEFF"
      # CSV.generate：対象データを自動的にCSV形式に変換してくれるCSVライブラリの一種
      csv_data = CSV.generate(bom, encoding: Encoding::SJIS, row_sep: "\r\n", force_quotes: true) do |csv|
        # %w()は空白で区切って配列を返す。
        column_names = %W(日付 曜日 出勤時間 退勤時間)
        # csv << column_namesは表の列に入る名前を定義
        csv << column_names
        # column_valuesに代入するカラム値を定義
        @attendances = @user.attendances.where(worked_on: @first_day..@last_day).order(:worked_on)
        @attendances.each do |day|
          column_values = [
            l(day.worked_on, format: :short),
            $days_of_the_week[day.worked_on.wday],
            if day.started_at.present? && (day.c_request == "承認").present?
              l(day.started_at.floor_to(60*15), format: :time)
            else
              ""
            end,
            if day.finished_at.present? && (day.c_request == "承認").present?
              l(day.finished_at.floor_to(60*15), format: :time)
            else
              ""
            end
          ]
        # csv << column_valueは表の行に入る値を定義
          csv << column_values
        end
      end
      # csv出力ファイル名を定義
      send_data(csv_data, filename: "【勤怠一覧】#{@user.name}_#{@first_day.strftime("%Y-%m")}.csv", type: :csv)
    end

    def query
      if params[:user].present? && params[:user][:name] != ""
        @search_value = User.where('name LIKE ?', "%#{params[:user][:name]}%")
      else
        User.all
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  # 勤怠基本情報を指定のフォーマットで返します。
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_edit_basic_info.html.erb
<% provide(:title, 'Basic info edit') %>
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :affiliation, class: "form-control" %>

            <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form_index.html.erb
<%= form_with(model: user, url: update_basic_info_user_path(user), local: true, method: :patch) do |f| %>
  <%= render 'shared/error_messages', object: @user = user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>

  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.number_field :employee_number, class: "form-control" %>

  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :uid, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_work_time, class: "form-control" %>

  <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_start_time, class: "form-control" %>

  <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_end_time, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/attendance_log.html.erb
<% provide(:title, @user.name) %>
<h1>【 勤怠ログ 】</h1>

<div class = "m5px">
  <%= form_with(model: @attendances, url: attendance_log_user_path(date: @first_day), method: :get, local: true) do |f| %>
    <%= f.month_field :worked_on, {} %>
    <%= f.submit '検索', class:"btn btn-sm btn-primary" %>
    <%= link_to "Reset", attendance_log_user_path(date: @first_day), class:"btn btn-sm btn-warning" %>
  <% end %>
</div>

  <table class="table table-bordered table-striped table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th>日付</th>
        <th>変更前出社時間</th>
        <th>変更前退社時間</th>
        <th>変更後出社時間</th>
        <th>変更後退社時間</th>
        <th>承認者</th>
      </tr>
    </thead>

    <% if @attendances.present? %>
      <% @attendances.each do |att| %>
        <tbody>
          <tr>
          <% if att.c_approval == "承認" %>
            <!--日付-->
            <td><%= l(att.worked_on, format: :long2) %></td>
            <!--変更前-->
            <td><%= l(att.c_bf_started_at, format: :time) if att.c_bf_started_at.present? %></td>
            <td><%= l(att.c_bf_finished_at, format: :time) if att.c_bf_finished_at.present? %></td>
            <!--変更後-->
            <td><%= l(att.c_af_started_at, format: :time) %></td>
            <td><%= l(att.c_af_finished_at, format: :time) %></td>
            <!--承認者-->
            <td><%= att.c_request %></td>
          <% end %>
        </tr>
      </tbody>
    <% end %>
  <% end %>
</table>

<div class="center">
  <%= link_to "勤怠へ戻る", user_path(date: @first_day), class: "btn btn-md btn-default" %>
</div>           

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text,'編集') %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'users/form' %>
  </div>
</div>

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit-basic-info").modal("show");

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '編集する') %>
<h1>ユーザー一覧</h1>

<!-- CSVインポート -->
<div class="">
  <%= form_tag import_users_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "CSVをインポート", class:"btn btn-primary" %>
  <% end %>
</div>

<!-- ユーザー検索 -->
<ul class="search-form">
  <%= form_with url: users_path, method: :get, local: true do |form| %>
    <%= form.text_field :search %>
    <%= form.submit '検索', name: nil %>
  <% end %>
</ul>

<% @users.each do |user| %>
  <% unless user.admin? %>
    <table>
      <div class="row">
        <tr>
          <%= user.name %><br>
          <td class="center">
            <%= "|" %>
              <%= link_to "削除", user, method: :delete,
                  data: { confirm: "削除してよろしいですか?" }, class: "btn btn-primary" %>
          </td>
        </tr>
      </div>
    </table>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <button type="button" class="btn btn-lg btn-primary" data-toggle="collapse" data-target="#collapse<%= user.id %>">編集</button>
        </h4>
      </div>
      <div id="collapse<%= user.id %>" class="panel-collapse collapse out">
        <div class="panel-body">
          <%= render 'users/form_index',{user: user} %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
<%= will_paginate %>

<!--モーダルウインドウ表示-->
<div id="edit-basic-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '作成') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'users/form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<!-- ユーザー情報テーブル -->
<div>
  <table class="table table-bordered table-striped table-condensed user-table">
    <tr>
      <td class="center">
        <% if current_user?(@user) %>
        <%= link_to "←", user_path(date: @first_day.prev_month), class: "btn btn-primary btn-sm" %>
        <% end %>
        <%= l(@first_day, format: :middle) %> 時間管理表
        <% if current_user?(@user) %>
        <%= link_to "→", user_path(date: @first_day.next_month), class: "btn btn-primary btn-sm" %>
        <% end %>
      </td>
      <td>
        指定勤務開始時間： <%= format_basic_info(@user.designated_work_start_time) %><br>
        指定勤務終了時間： <%= format_basic_info(@user.designated_work_end_time) %>
      </td>
      <td colspan="3">基本勤務時間：<%= format_basic_info(@user.basic_work_time) %></td>
      <td class="center">初日：<%= l(@first_day, format: :short) %></td>
    </tr>
    
    <tr>
      <td>所属：<%= @user.affiliation.present? ? @user.affiliation : "未所属" %></td>
      <td>氏名：<%= @user.name %></td>
      <td>コード：</td>
      <td><%= @user.employee_number %></td>
      <td>出勤日数 <%= @worked_sum %>日</td>
      <td>締め <%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<!-- 申請お知らせ -->
<div>
  <% if @user.superior? && current_user?(@user) %>
    <% if @r_count >= 1 %>
      <%= link_to "【所属長承認申請のお知らせ】", reports_notice_report_user_path, remote: true, style:"color:#f00" %>
      <span class="box1"><%= "#{@r_count}件の通知があります" %></span><br>
    <% else %>
      <%= "【所属長承認申請のお知らせ】" %><br>
    <% end %>

    <% if @a_count >= 1 %>
      <%= link_to "【勤怠変更申請のお知らせ】", attendances_notice_change_at_user_path, remote: true, style:"color:#f00" %>
      <span class="box1"><%= "#{@a_count}件の通知があります" %></span><br>
    <% else %>
      <%= "【勤怠変更申請のお知らせ】" %><br>
    <% end %>

    <% if @o_count >= 1 %>
      <%= link_to "【残業申請のお知らせ】", attendances_notice_overtime_user_path, remote: true, style:"color:#f00" %>
      <span class="box1"><%= "#{@o_count}件の通知があります" %></span><br>
    <% else %>
      <%= "【残業申請のお知らせ】" %><br>
    <% end %>
  <% end %>
</div>

<!-- 勤怠の編集や出力を行うボタン -->
<div class="btn-users-show">
  <% if current_user?(@user) %>
    <span class="m5px">
      <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
    </span>
    <span><%= link_to "CSV出力", user_path(@user, date: @first_day, format: :csv), class: "btn btn-primary" %><br></span>
    <div class="m5px">
      <%= link_to "勤怠修正ログ（承認済）", attendance_log_user_path(date: @first_day), class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

<!-- 勤怠テーブル -->
<table class="table table-bordered table-striped table-condensed table-hover" id="table-attendances">
  <thead>
    <tr>
      <th rowspan="3">残業申請</th>
      <th rowspan="3">日付</th>
      <th rowspan="3">曜日</th>
      <th colspan="8">【実績】</th>
      <th colspan="5">所定外勤務</th>
    </tr>
    <tr>
      <th colspan="3">出社</th>
      <th colspan="3">退社</th>
      <th rowspan="2">在社時間</th>
      <th rowspan="2">備考</th>
      <th colspan="2">終了予定時間</th>
      <th rowspan="2">時間外残業</th>
      <th rowspan="2">業務処理内容</th>
      <th rowspan="2">指示者確認 ㊞</th>
    </tr>
    <tr>
      <th>時</th>
      <th>分</th>
      <th></th>
      <th>時</th>
      <th>分</th>
      <th></th>
      <th>時</th>
      <th>分</th>
    </tr>
  </thead>
  
  <tbody>
    <% @attendances.each do |oneday| %>
      <tr>
        <!-- 残業申請ボタン -->
        <td>
          <% if current_user?(@user) %>
            <%= link_to "残業申請", attendances_req_overtime_user_path(params: { att_id: oneday ,date: @first_day } ), remote: true, class: "btn btn-primary" %>
          <% end %>
        </td>
        
        <!-- 日付 -->
        <td><%= l(oneday.worked_on, format: :short) %></td>
        
        <!-- 曜日 -->
        <td class = '<%= "wday#{oneday.worked_on.wday}"%>'>
          <%= $days_of_the_week[oneday.worked_on.wday] %>
        </td>

        <!-- 出社：時、分 -->
        <td><%= l(oneday.started_at.floor_to(15.minutes), format: :hour) if oneday.started_at.present? %></td>
        <td><%= l(oneday.started_at.floor_to(15.minutes), format: :minit) if oneday.started_at.present? %></td>
        
        <!-- 出社ボタン -->
        <td>
          <% if (Date.current == oneday.worked_on) && oneday.started_at.nil? %>
            <%= link_to "出勤", user_attendance_path(@user, oneday), method: :patch, class: "btn btn-primary btn-attendance" %>
          <% end %>
        </td>

        <!-- 退社：時、分 -->
        <td><%= l(oneday.finished_at.floor_to(15.minutes), format: :hour) if oneday.finished_at.present? %></td>
        <td><%= l(oneday.finished_at.floor_to(15.minutes), format: :minit) if oneday.finished_at.present? %></td>
        
        <!-- 退社ボタン -->
        <td>
          <% if (Date.current == oneday.worked_on) && oneday.started_at.present? && oneday.finished_at.nil? %>
            <%= link_to "退勤", user_attendance_path(@user, oneday), method: :patch, class: "btn btn-primary btn-attendance" %>
          <% end %>
        </td>

        <!-- 在社時間 -->
        <td>
          <% if oneday.started_at.present? && oneday.finished_at.present? %>
            <%= str_times = working_times(oneday.started_at, oneday.finished_at) %>
            <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
          <% end %>
        </td>

        <!-- 備考 -->
        <td><%= oneday.note %></td>

        <% if oneday.end_time.present? && !oneday.o_request.nil? %>
        <!-- 終了予定時間：時、分 -->
        <td><%= oneday.end_time.hour %></td>
        <td><%= oneday.end_time.min %></td>

        <!-- 時間外残業 -->
        <td>
          <% if oneday.overtime < 0 %>
            <%= "0 h" %>
          <% else %>
            <%= "#{oneday.overtime} h" %>
          <% end %>
        </td>
        <% else %>
          <td></td>
          <td></td>
          <td></td>
        <% end %>

        <!-- 業務処理内容 -->
        <td><%= oneday.business_process %></td>

        <!-- 指示書確認㊞ -->
        <td>
          <div class="text-left">
          <% case oneday.o_approval %>
            <% when 'なし' then %>
              <%= "" %>
            <% when '申請中' then %>
              <%= "・#{oneday.o_request}へ残業申請中" %><br>
            <% when '承認' then %>
              <%= "〇 残業承認済" %><br>
            <% when '否認' then %>
              <%= "× 残業否認" %><br>
          <% end %>
          <% case oneday.c_approval %>
            <% when 'なし' then %>
              <%= "" %>
            <% when '申請中' then %>
              <%= "・#{oneday.c_request}へ勤怠変更申請中" %>
            <% when '承認' then %>
              <%= "〇 勤怠変更承認済" %>
            <% when '否認' then %>
              <%= "× 勤怠変更否認" %>
          <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr>
      <td rowspan="2"></td>
      <td colspan="2"><%= @attendances.count %></td>
      <td colspan="6"></td>
      <td><%= format("%.2f", @total_working_times.to_f) %></td>
      <td colspan="5"></td>
      <td rowspan="2">
        <% if current_user?(@user) %>
          <span class="approval"><%= "所属長承認" %></span><br>
          
          <% @report_month = Report.where(r_month: @first_day.month, user_id: @user).first %>
          <% if @report_month.present? %>
            <%= "#{@report_month.r_request} [#{@report_month.r_approval}]" %><br>
          <% else %>
            <%= "未申請" %><br>
          <% end %>

          <%= form_with(model: @reports, url: user_reports_path(@user), local: true, method: :post) do |f| %>
            <%= f.hidden_field :first_day, :value => @first_day %>
            <%= f.hidden_field :r_approval, :value => "申請中" %>

            <div class="dropdown_menu2">
              <% if @user.name == "上長A" %>
                <%= f.select :r_request, ['', '上長B', 'テスト1'], {:selected =>''} %>
              <% elsif @user.name == "上長B" %>
                <%= f.select :r_request, ['', '上長A', 'テスト1'], {:selected =>''} %>
              <% else %>
                <%= f.select :r_request, ['', '上長A', '上長B', 'テスト1'], {:selected =>''} %>
              <% end %>
            </div>
            <%= f.submit "申請", class: "btn btn-primary w-100px" %>
          <% end %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td colspan="2"><%= @attendances.count %></td>
      <td colspan="6"></td>
      <td><%= format("%.2f", @total_working_times.to_f) %></td>
      <td colspan="5"></td>
    </tr>
  </tfoot>
</table>

<!-- ボタン -->
<div class="center">
  <%= link_to "↑", user_path(date: @first_day), class: "btn btn-default" %>
  <% if @user.admin? %>
    <%= link_to "ユーザー一覧へ", users_path, class: "btn btn-default" %>
  <% end %>
</div>

<!-- モーダルウインドウ -->
<div>
  <!-- [残業申請モーダル] -->
  <div id="req_overtime" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
  
  <!-- [所属長承認申請のお知らせ] -->
  <div id="notice_report" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

  <!-- [勤怠変更申請のお知らせ] -->
  <div id="notice_change_at" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

  <!-- [残業申請のお知らせ] -->
  <div id="notice_overtime" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
</div>