config/routes.rb
Rails.application.routes.draw do
  get 'bases/new'

  get 'sessions/new'

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン機能
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
 
  resources :users do
    member do
      get 'edit_basic_info'
      get 'edit_basic_info_admin'
      get 'working_list'
      patch 'update_basic_info'
      get 'attendance_log'
      get 'csv_export'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'

      get 'attendances/req_overtime'
      patch 'attendances/update_overtime'
      get 'attendances/notice_overtime'
      patch 'attendances/update_notice_overtime'
      get 'attendances/notice_change_at'
      patch 'attendances/update_notice_change_at'
      get 'reports/notice_report'
      patch 'reports/update_report'
    end
    collection {post :import}
    resources :attendances, only: :update
    resources :reports, only: :create
  end
  resources :bases do
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  
  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }

# 残業申請バリデーション
  validates :o_request, presence: true, on: :overtime_update
  validates :business_process, presence: true, on: :overtime_update
  
  # 出勤時間が存在しない場合、残業時間は無効
  validate :finished_at_is_invalid_without_a_started_at, on: :overtime_update

  # 翌日⁼falseの場合、出社時間より早い終了予定時間は無効
  validate :started_at_than_finished_at_fast_if_invalid, on: :overtime_update

  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が未入力です。") if started_at.blank? && finished_at.present?
  end
  
  def started_at_than_finished_at_fast_if_invalid
    errors.add(:started_at, "より早い退勤時間が入力されています。") if started_at > finished_at && o_nextday == false
  end

# 勤怠変更申請のバリデーション
  # 必要なアイテム検証
  validate :need_item, on: :attendance_update

  # 出社・退社時間どちらも存在し、翌日⁼falseの場合、出社時間より早い退社時間は無効
  validate :started_at_than_finished_at_fast_if_invalid, on: :attendance_update

  # 在社時間は24時間以上
  validate :total_working_over24h, on: :attendance_update

  def need_item
    errors.add(:started_at, "の入力が不足しています") if c_af_finished_at.blank?
    errors.add(:finished_at, "の入力が不足しています") if c_af_started_at.blank?
    errors.add(:note, "の入力が不足しています") if note.blank?
  end

  def started_at_than_finished_at_fast_if_invalid
    if c_af_started_at.present? && c_af_finished_at.present? && c_af_nextday == false
      errors.add(:started_at, "より早い退勤時間は無効です") if c_af_started_at > c_af_finished_at
    end
  end

  def total_working_over24h
    if c_af_started_at.present? && c_af_finished_at.present? && c_bf_nextday == true
      @total = ((c_af_finished_at.since(1.days) - c_af_started_at) / 3600)
      errors.add(:company_time, "が24時間をオーバーしています") unless @total < 24
    end
  end

end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:edit_one_month, :update_one_month, :req_overtime, :update_overtime, :notice_overtime, :update_notice_overtime, :notice_change_at, :update_notice_change_at, :attendance_log]
  # アクセス先のログインユーザーor上長（管理者も不可）
  before_action :admin_or_correct_user, only: [:edit_one_month, :update_one_month]
  # ログイン中のユーザーか
  before_action :logged_in_user, only: [:update_one_month, :edit_one_month]
  # アクセス先のログインユーザーか
  before_action :correct_user, only: [:edit_one_month, :update_one_month]
  # 1か月分の勤怠情報を取得
  before_action :set_one_month, only: [:edit_one_month, :req_overtime, :update_overtime]
  
  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。"
  NOTICE_ERROR_MSG = "入力が足りません。"

  # 出退勤ボタン
  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    # 出勤時間が未登録であることを判定
    if @attendance.started_at.nil?
      unless @attendance.c_approval == "申請中"
        if @attendance.update_attributes(started_at: Time.current.change(sec: 0),
                                        c_af_started_at: Time.current.change(sec: 0))
          flash[:info] = "おはようございます！"
        else
          flash[:danger] = UPDATE_ERROR_MSG + @attendance.errors.full_messages.join
        end
      else
        if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
          flash[:info] = "おはようございます！"
        else
          flash[:danger] = UPDATE_ERROR_MSG + @attendance.errors.full_messages.join
        end
      end
    elsif @attendance.finished_at.nil?
      unless @attendance.c_approval == "申請中"
        if @attendance.update_attributes(finished_at: Time.current.change(sec: 0),
                                        c_af_finished_at: Time.current.change(sec: 0))
          flash[:info] = "お疲れさまでした。"
        else
          flash[:danger] = UPDATE_ERROR_MSG
        end
      else
        if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
          flash[:info] = "お疲れさまでした。"
        else
          flash[:danger] = UPDATE_ERROR_MSG
        end
      end
    end
    redirect_to @user
  end
  
  # 勤怠編集画面
  def edit_one_month
  end
  
  # 勤怠変更申請の送信
  def update_one_month
    @count = 0 # 申請完了件数のカウンター
    ActiveRecord::Base.transaction do # トランザクションを開始。
      attendances_params.each do |id, item|
        @attendance = Attendance.find(id)
        @attendance.attributes = item

        # 現在日以前のみ確認
        if @attendance.worked_on <= Date.current
      
          # 申請先選択済みかつ既に申請中でない
          if @attendance.c_request.present? && @attendance.c_approval != "申請中"
            @attendance.c_af_started_at = make_time(@attendance, "start")
            @attendance.c_af_finished_at = make_time(@attendance, "finish")

            # 変更前の履歴を保存
            @attendance.c_bf_started_at = @attendance.started_at if @attendance.started_at.present?
            @attendance.c_bf_finished_at = @attendance.finished_at if @attendance.finished_at.present?

            @attendance.c_approval = "申請中"
            if @attendance.save!(context: :attendance_update)
              @count += 1
            end
          end
        end
      end
    end
    if @count > 0
      flash[:success] = "勤怠情報の編集申請を#{@count}件送信しました。"
      redirect_to user_url(date: params[:date])
    else
      flash[:warning] = "申請先が未選択です。"
      redirect_to attendances_edit_one_month_user_url(date: params[:date])
    end
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐
    flash[:danger] = "<li>" + @attendance.errors.full_messages.join("</li><li>")
    redirect_to attendances_edit_one_month_user_url(date: params[:date])
  end

  # 勤怠変更申請のお知らせフォーム
  def notice_change_at
    @notice_user = User.where(id: Attendance.where(c_request: @user.name, c_approval: "申請中").select(:user_id))
    @attendance_lists = Attendance.where(c_request: @user.name, c_approval: "申請中")
  end

  # 勤怠変更申請のお知らせフォーム *承認状態の変更
  def update_notice_change_at
    @count = [0,0,0]
    ActiveRecord::Base.transaction do # トランザクションを開始
      notice_change_at_params.each do |id, item|
        attendance = Attendance.find(id)
        attendance.attributes = item
        if attendance.change && attendance.c_approval != "申請中"
          if attendance.c_approval == "承認"
            
            # メインの勤怠一覧用の時間を置き換える
            attendance.started_at = attendance.c_af_started_at
            attendance.finished_at = attendance.c_af_finished_at
            attendance.c_bf_nextday = attendance.c_af_nextday

            attendance.o_nextday = true if attendance.c_bf_nextday
            attendance.c_approval_date = Time.now
            if attendance.save!
              @count[0] += 1
            end
          else
            attendance.note = nil
            attendance.c_bf_nextday = false
            # 変更前が存在する場合は置き換える
            attendance.c_af_started_at = attendance.started_at
            attendance.c_af_finished_at = attendance.finished_at
            attendance.c_af_nextday = false
            attendance.c_request = nil
            attendance.change = false
            if attendance.save!
              @count[1] += 1 if attendance.c_approval == "否認"
              @count[2] += 1 if attendance.c_approval == "なし"
              end
              end
            end
          end
        end
        unless @count.sum == 0
          flash[:success] = "#{@count.sum}件の申請を更新しました。（承諾：#{@count[0]}件、否認：#{@count[1]}件、なし：#{@count[2]}件）"
        else
          flash[:warning] = "更新できる申請がありません。"
        end
        redirect_to user_url(@user)
      rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐
        flash[:danger] = NOTICE_ERROR_MSG
        redirect_to user_url(@user)
      end

      # 残業申請フォーム
      def req_overtime
        @att_id = @user.attendances.find(params[:att_id].to_i)

        # 申請していない場合、デフォルト時間を00:00へ設定
        if @att_id.o_request.nil?
          @att_id.end_time = Time.current.change(year: @att_id.worked_on.year, month: @att_id.worked_on.month,
                                                  day: @att_id.worked_on.day, hour: '0', min: '0', sec: '0')
          @att_id.save
        end
      end

      # 残業申請の送信
      def update_overtime
        @total = 0
        ActiveRecord::Base.transaction do #トランザクションを開始
          req_overtime_params.each do |id, item|
            @attendance = Attendance.find(id)
            @attendance.attributes = item
            # 残業時間の計算
            if @attendance.started_at.blank?
              @started_nil = true
            else
              @total = overtime_calc(@attendance)
              if @total <= 24
                @attendance.o_approval = '申請中'
                @attendance.save!(context: :overtime_update)
                @worked_on = l(@attendance.worked_on, format: :short)
                @o_request = @attendance.o_request
              end
            end
          end
        end
        if @started_nil
          flash[:danger] = "出社時間が入力されていません。"
        elsif @total <= 24
          flash[:success] = "#{@worked_on}の残業申請を\"#{@o_request}\"へ送信しました。"
        else
          flash[:danger] = "在社時間が24時間をオーバーしています。"
        end
        redirect_to user_url(date: @first_day)
      rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐
        flash[:danger] = @attendance.errors.full_messages.join
        redirect_to user_url(date: @first_day)
      end

  # 残業申請通知フォーム
  def notice_overtime
    @notice_user = User.where(id: Attendance.where(o_request: @user.name, o_approval: "申請中").select(:user_id))
    @attendance_lists = Attendance.where(o_request: @user.name, o_approval: "申請中")
  end

  # 残業申請通知フォーム
  def update_notice_overtime
    @count = [0,0,0]
    ActiveRecord::Base.transaction do # トランザクション開始
      notice_overtime_params.each do |id, item|
        attendance = Attendance.find(id)
        attendance.attributes = item
        if attendance.change && attendance.o_approval != "申請中"
          if attendance.o_approval == "承認"
            attendance.finished_at = attendance.end_time
            attendance.c_af_finished_at = attendance.end_time
            attendance.c_bf_nextday = true if attendance.o_nextday
            if attendance.save!
              @count[0] += 1
            end
          else
            attendance.end_time = nil
            attendance.overtime = nil
            attendance.o_request = nil
            attendance.o_nextday = false
            attendance.business_process = nil
            if attendance.save!
              @count[1] += 1 if attendance.o_approval == "否認"
              @count[2] += 1 if attendance.o_approval == "なし"
            end
          end
        end
      end
    end
    unless @count.sum == 0
      flash[:success] = "#{@count.sum}件の申請を更新しました。 （承諾：#{@count[0]}件、否認：#{@count[1]}件、なし：#{@count[2]}件）"
    else
      flash[:warning] = "変更にチェックがなかったため中止しました。"
    end
    redirect_to user_url(@user)
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐
    flash[:danger] = NOTICE_ERROR_MSG
    redirect_to user_url(@user)
  end

  private
  
    # 1か月分の勤怠情報を扱います。
    def attendances_params
      params.require(:user).permit(attendances: [:c_af_started_at, :c_af_finished_at, :c_af_nextday, :c_request, :note])[:attendances]
    end
    
    # 通知のあった勤怠変更申請の承認内容を扱います。
    def notice_change_at_params
      params.require(:user).permit(attendances: [:c_approval, :change])[:attendances]
    end

    # 残業時間申請内容を扱います。
    def req_overtime_params
      params.require(:user).permit(attendances: [:end_time, :overtime, :o_nextday, :business_process, :o_request])[:attendances]
    end

    # 通知のあった残業時間申請の承認内容を扱います。
    def notice_overtime_params
      params.require(:user).permit(attendances: [:o_approval, :change])[:attendances]
    end

    # 残業時間の計算
    def overtime_calc(at)
      # 比較計算用 指定勤務終了時間の作成
      @work_end_time = (Time.local(at.end_time.year,
                              at.end_time.month,
                              at.end_time.day,
                              @user.designated_work_end_time.hour,

app/helpers/attendances_helper.rb
module AttendancesHelper

  def attendance_state(attendance)
    # 受け取ったAttendanceオブジェクトが当日と一致するかを評価
    if Date.current == attendance.worked_on
      return '出社' if attendance.started_at.nil?
      return '退社' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    # 出社でも退社でもない場合はfalse
    false
  end
  
  # 出社時間と退社時間を受け取り、在社時間を計算
  def working_times(start, finish)
    format("%.2f", ((finish - start) / 60 / 60.0))
  end
  
  # 出社時間と退社時間を受け取り、在社時間を計算
  def working_times_check_nextday(attendance)
    start = attendance.started_at.floor_to(15.minutes)

    if attendance.c_bf_nextday
      finish = attendance.finished_at.since(1.days).floor_to(15.minutes)
      format("%.2f", (((finish - start) / 60) / 60.0))
    else
      finish = attendance.finished_at.floor_to(15.minutes)
      format("%.2f", (((finish - start) / 60) / 60.0))
    end
  end
end

app/views/attendances/_notice_change_at.html.erb
<% provide(:title, 'notice_change_at') %>
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <!-- ×マーク -->
    <div class="modal-header" style="border:none">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-11 position">

          <%= form_with(model: @user, url: attendances_update_notice_change_at_user_path, local: true, method: :patch) do |f| %>
            <% @notice_user.each do |notice_user| %>
              <h1 class="modal-title" style="text-align:center"><%= "【#{notice_user.name}からの1か月分の勤怠申請】" %></h1>
              <table class="table table-bordered table-striped table-hover" id="table-attendances">
                <thead>
                  <tr>
                    <th rowspan="3">日付</th>
                    <th rowspan="3">曜日</th>
                    <th colspan="4">変更前</th>
                    <th colspan="4">変更後</th>
                    <th rowspan="3">備考</th>
                    <th rowspan="3">指示者確認㊞</th>
                    <th rowspan="3">変更</th>
                    <th rowspan="3">勤怠を確認する</th>
                  </tr>
                  <tr>
                    <th colspan="2">出社</th>
                    <th colspan="2">退社</th>
                    <th colspan="2">出社</th>
                    <th colspan="2">退社</th>
                  </tr>
                  <tr>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                  </tr>
                </thead>

                <% @attendance_lists.where(user_id: notice_user.id).each do |ats| %>
                  <%= f.fields_for "attendances[]", ats do |at| %>
                  <tbody>
                    <tr>
                      <!-- 日付 -->
                      <td class="center"><%= l(ats.worked_on, format: :short) %></td>
                      <!-- 曜日 -->
                      <td class = '<%= "wday#{ats.worked_on.wday}" %>'>
                        <%= $days_of_the_week[ats.worked_on.wday] %>
                      </td>
                      <!-- 変更前 出社時間 -->
                      <td class="center"><%= ats.started_at.hour if ats.started_at.present? %></td>
                      <td class="center"><%= ats.started_at.min if ats.started_at.present? %></td>
                      <!-- 変更前 退社時間 -->
                      <td class="center"><%= ats.finished_at.hour if ats.finished_at.present? %></td>
                      <td class="center"><%= ats.finished_at.min if ats.finished_at.present? %></td>
                      <!-- 変更後 出社時間 -->
                      <td class="center"><%= ats.c_af_started_at.hour %></td>
                      <td class="center"><%= ats.c_af_started_at.min %></td>
                      <!-- 変更後 退社時間 -->
                      <td class="center"><%= ats.c_af_finished_at.hour %></td>
                      <td class="center"><%= ats.c_af_finished_at.min %></td>
                      <!-- 備考 -->
                      <td class="center"><%= ats.note %></td>
                      <!-- 指示者確認㊞ -->
                      <td class="dropdown_menu">
                        <%= at.select :c_approval, ['', 'なし', '申請中', '承認', '否認'], {} %>
                      </td>
                      <!-- 変更 -->
                      <td class="center"><%= at.check_box :change, {:checked => false} %></td>
                      <!-- 勤怠の確認 -->
                      <td class="center">
                        <%= link_to "確認", user_path(notice_user.id, date: "2022-#{ats.worked_on.month}-01"), :target=>["_new"], class: "btn btn-sm btn-primary" %>
                      </td>
                    </tr>
                  </tbody>
                  <% end %>
                <% end %>

              </table>
            <% end %>

            <!-- ボタン -->
            <div class="center">
              <%= link_to "キャンセル", user_url(@user), class: "btn btn-md btn-default" %>
              <%= f.submit "変更を送信する", class: "btn btn-md btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_notice_overtime.html.erb
<% provide(:title, 'notice_overtime') %>
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <!-- ×マーク -->
    <div class="modal-header" style="border:none">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12 position">

          <%= form_with(model: @user, url: attendances_update_notice_overtime_user_path, local: true, method: :patch) do |f| %>
            <% @notice_user.each do |notice_user| %>
              <h4 class="modal-title" style="text-align:center"><%= "【#{notice_user.name}からの残業申請】" %></h4>
              <table class="table table-bordered table-striped table-position table-hover">
                <thead>
                  <tr>
                    <th>日付</th>
                    <th>曜日</th>
                    <th>終了予定時間</th>
                    <th>指定終了予定時間</th>
                    <th>時間外残業</th>
                    <th>業務処理内容</th>
                    <th>指示者確認㊞</th>
                    <th>変更</th>
                    <th><%= "勤怠を確認する" %></th>
                  </tr>
                </thead>

                <% @attendance_lists.where(user_id: notice_user.id).each do |ats| %>
                  <%= f.fields_for "attendances[]", ats do |at| %>
                  <tbody>
                    <tr>
                      <!-- 日付 -->
                      <td class="center"><%= l(ats.worked_on, format: :short) %></td>
                      <!-- 曜日 -->
                      <td class = '<%= "wday#{ats.worked_on.wday}" %>'>
                        <%= $days_of_the_week[ats.worked_on.wday] %>
                      <!-- 終了予定時刻 -->
                      <td class="center"><%= l(ats.end_time, format: :time) %></td>
                      <!-- 指定勤務終了時間 -->
                      <td class="center"><%= l(notice_user.designated_work_end_time, format: :time) %></td>
                      <!-- 時間外残業 -->
                      <td class="center"><%= "#{ats.overtime} h" %></td>
                      <!-- 業務処理内容 -->
                      <td class="center"><%= ats.business_process %></td>
                      <!-- 指示者確認㊞ -->
                      <td class="dropdown_menu">
                        <%= at.select :o_approval, ['', 'なし', '申請中', '承認', '否認'], {} %>
                      </td>
                      <!-- 変更 -->
                      <td class="center"><%= at.check_box :change, {:checked => false} %></td>
                      <!-- 勤怠の確認 -->
                      <td>
                        <%= link_to "確認", user_path(notice_user.id, date: "2022-#{ats.worked_on.month}-01"), :target=>["_new"], class: "btn btn-sm btn-primary" %>
                      </td>
                    </tr>
                  </tbody>
                  <% end %>
                <% end %>

              </table>
            <% end %>

          <!-- ボタン -->
          <div class="center">
            <%= link_to "キャンセル", user_url(@user), class: "btn btn-md btn-default" %>
            <%= f.submit "変更を送信する", class: "btn btn-md btn-primary" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/attendances/_req_overtime.html.erb
<% provide(:title, 'req_overtime') %>
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <!-- ×マーク-->
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
       <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">

          <%= form_with(model: @user, url: attendances_update_overtime_user_path(date: @first_day), local: true, method: :patch) do |f| %>
            <h4 class="modal-title" style="text-align:center">【残業申請】</h4>
            <table class="table table-bordered table-striped table-position table-hover">      
              <thead>
                <tr>
                  <th>日付</th>
                  <th>曜日</th>          
                  <th>終了予定時間</th>            
                  <th>翌日</th>
                  <th>業務処理内容</th>
                  <th>指示者確認㊞</th>
                </tr>
              </thead>

              <%= f.fields_for "attendances[]", @att_id do |attendance| %>
                <tbody>
                  <tr>
                    <!-- 日付 -->
                    <td><%= l(@att_id.worked_on, format: :short) %></td>
                    <!-- 曜日 -->
                    <td><%= $days_of_the_week[@att_id.worked_on.wday] %></td>
                    <!-- 終了予定時刻 -->
                    <td><%= attendance.time_field :end_time, class: "form-control" %></td>
                    <!-- 翌日 -->
                    <td><%= attendance.check_box :o_nextday, id: "o_next_day" %></td>
                    <!-- 業務処理内容 -->
                    <td><%= attendance.text_field :business_process, class: "form-control" %></td>            
                    <!-- 指示者確認㊞ -->
                    <td class="dropdown_menu">
                      <% if @user.name == "上長A" %>
                        <%= attendance.select :o_request, ['', '上長B', 'テスト1'], {:selected =>''} %>
                      <% elsif @user.name == "上長B" %>
                        <%= attendance.select :o_request, ['', '上長A', 'テスト1'], {:selected =>''} %>
                      <% else %>
                        <%= attendance.select :o_request, ['', '上長A', '上長B', 'テスト1'], {:selected =>''} %>
                      <% end %>
                    </td>
                  </tr>                  
                </tbody> 
              <% end %>

            </table>

            <div class="center">        
              <%= f.submit "残業を申請する", class: "btn btn-lg btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
<h1>勤怠編集画面</h1>
  <table class="table table-bordered table-striped table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th>日付</th>
        <th>曜日</th>
        <th>出社</th>
        <th>退社</th>
        <th>翌日</th>
        <th>在社時間</th>
        <th>備考</th>
        <th>指示者確認㊞</th>
      </tr>
    </thead>
    
    <tbody>
      <% @attendances.each do |att| %>
        <%= f.fields_for "attendances[]", att do |attendance| %>
          
          <tr>
            <!-- 日付 -->
            <td><%= l(att.worked_on, format: :short) %></td>
            <!-- 曜日 -->
            <td class = '<%= "wday#{att.worked_on.wday}" %>'>
              <%= $days_of_the_week[att.worked_on.wday] %>
            </td>

            <!-- 出社、退社（現在日以降は申請不可 -->
            <% if Date.current < att.worked_on %>
              <td><%= attendance.time_field :c_af_started_at, readonly: true, class: "form-control" %></td>
              <td><%= attendance.time_field :c_af_finished_at, readonly: true, class: "form-control" %></td>
            <% else %>
              <td><%= attendance.time_field :c_af_started_at, class: "form-control" %></td>
              <td><%= attendance.time_field :c_af_finished_at, class: "form-control" %></td>
            <% end %>
            <!-- 翌日 -->
            <td><%= attendance.check_box :c_af_nextday, {} %></td>

            <!-- 在社時間 -->
            <td>
              <% if att.started_at.present? && att.finished_at.present? %>
                <%= working_times_check_nextday(att) %>
              <% end %>
            </td>
            <!-- 備考 -->
            <td><%= attendance.text_field :note, class: "form-control" %></td>

            <!-- 指示者確認㊞ -->
            <td class="dropdown_menu">
              <% if @user.name == "上長A" %>
                <% @array = ['', '上長B', 'テスト1'] %>
              <% elsif @user.name == "上長B" %>
                <% @array = ['', '上長A', 'テスト1'] %>
              <% else %>
                <% @array = ['', '上長A', '上長B', 'テスト1'] %>
              <% end %>

              <% if att.c_approval == "承認" %>
                <%= attendance.select :c_request, @array.map { |item| item }, {selected: ""} %>
              <% else %>
                <%= attendance.select :c_request, @array.map { |item| item }, {} %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  
  <div class="center">
    <%= link_to "↑", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-default" %>
    <%= link_to "勤怠へ戻る", user_path(date: @first_day), class: "btn btn-md btn-default" %>
    <%= f.submit "編集を保存する", class: "btn btn-md btn-primary" %>
  </div>
<% end %>

app/views/attendances/notice_change_at.js.erb
$("#notice_change_at").html("<%= escape_javascript(render 'notice_change_at') %>");
$("#notice_change_at").modal("show");

app/views/attendances/notice_overtime.js.erb
$("#notice_overtime").html("<%= escape_javascript(render 'notice_overtime') %>");
$("#notice_overtime").modal("show");

app/views/attendances/req_overtime.js.erb
$("#req_overtime").html("<%= escape_javascript(render 'req_overtime') %>");
$("#req_overtime").modal("show");