config/routes.rb
Rails.application.routes.draw do
  get 'bases/new'

  get 'sessions/new'

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン機能
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
 
  resources :users do
    member do
      get 'edit_basic_info'
      get 'edit_basic_info_admin'
      get 'working_list'
      patch 'update_basic_info'
      get 'attendance_log'
      get 'csv_export'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'

      get 'attendances/req_overtime'
      patch 'attendances/update_overtime'
      get 'attendances/notice_overtime'
      patch 'attendances/update_notice_overtime'
      get 'attendances/notice_change_at'
      patch 'attendances/update_notice_change_at'
      get 'reports/notice_report'
      patch 'reports/update_report'
    end
    collection {post :import}
    resources :attendances, only: :update
    resources :reports, only: :create
  end
  resources :bases do
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user

  validates :r_request, presence: true
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_user, only: [:notice_report, :update_report]
  before_action :set_one_month, only: :notice_report

  NOTICE_ERROR_MSG = "入力が足りません。申請をやり直してください。"

  def create
    first_day = Date.strptime(params[:first_day],'%Y-%m-%d')
    @user = User.find(params[:user_id])
    report = @user.reports.where(r_month: first_day.month.to_i, user_id: params[:user_id]).first
    if report.present?
      if report.update_attributes(report_params)
        flash[:success] = "#{first_day.month}月の月次申請先を\"#{report.r_request}\"へ変更しました。"
      else
        flash[:danger] = "月次申請は失敗しました。<br><li>" + report.errors.full_messages.join("</li><li>")
      end
    else
      report = @user.reports.create(report_params)
      report.r_month = first_day.month.to_i
      if report.save
        flash[:success] = "\"#{report.r_request}\"へ#{first_day.month}月の月次申請先を送信しました。"
      else
        flash[:danger] = "月次申請は失敗しました。<br><li>" + report.errors.full_messages.join("</li><li>")
      end
    end
    redirect_to user_path(@user,date: first_day)
  end

  def notice_report
    @notice_user = User.where(id: Report.where(r_request: @user.name, r_approval: "申請中").select(:user_id))
    @report_lists = Report.where(r_request: @user.name, r_approval: "申請中")
  end

  def update_report
    @count = [0,0,0]
    ActiveRecord::Base.transaction do # トランザクションを開始
      notice_report_params.each do |id,item|
        report = Report.find(id)
        report.attributes = item
        if report.change
          @count[0] = @count[0] + 1 if report.r_approval == "なし"
          @count[1] = @count[1] + 1 if report.r_approval == "承認"
          @count[2] = @count[2] + 1 if report.r_approval == "否認"
          report.save!
        end
      end
    end
    unless @count.sum == 0
      flash[:success] = "#{@count.sum}件の申請を更新しました。（なし：#{@count[0]}件、承認：#{@count[1]}件、否認：#{@count[2]}件）"
    else
      flash[:warning] = "変更にチェックがなかったため、中止しました。"
    end
    redirect_to user_url(@user)
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐
    flash[:danger] = NOTICE_ERROR_MSG
    redirect_to user_url(@user)
  end

  private

    # 所属長承認申請内容
    def report_params
      params.permit(:r_approval, :r_request, :user_id)
    end

    # 通知のあった所属長承認申請を扱う。
    def notice_report_params
      params.require(:user).permit(reports: [:r_month, :r_approval, :change, :user_id])[:reports]
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_notice_report.html.erb
<% provide(:title, @user.name) %>
<div class="modal-dialog modal-md modal-dialog-center">
  <div class="modal-content">
      <!-- ×マーク -->
    <div class="modal-header" style="border:none">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-10 position">

        <%= form_with(model: @user, url: reports_update_report_user_path, local: true, method: :patch ) do |f| %>
          <% @notice_user.each do |notice_user| %>
            <h4 class="modal-title" style="text-align:center"><%="【#{notice_user.name}からの1ヶ月分勤怠申請】" %></h4>
            <table class="table table-bordered table-striped table-position table-hover">
              <thead>
                <tr>
                  <th>月</th>
                  <th>指示者確認㊞</th>
                  <th>変更</th>
                  <th>勤怠を確認する</th>
                </tr>
              </thead>

              <% @report_lists.where(user_id: notice_user.id).each do |report| %>
                <%= f.fields_for "reports[]", report do |rep| %>
                <tbody>
                  <tr>
                    <!-- 月 -->
                    <td class="center"><%= report.r_month %></td>
                    <!-- 指示書確認㊞ -->
                    <td class="dropdown_menu">
                      <%= rep.select :r_approval, ['', 'なし', '申請中', '承認', '否認'], {} %>
                    </td>
                    <!-- 変更 -->
                    <td class="center"><%= rep.check_box :change, {:checked => false} %></td>
                    <!-- 勤怠の確認 -->
                    <td>
                      <%= link_to "確認", user_path(notice_user.id, date: "2022-#{report.r_month}-01"), :target=>["_new"], class: "btn btn-sm btn-primary" %>
                    </td>
                  </tr>
                </tbody>
                <% end %>
              <% end %>

            </table>
          <% end %>

          <!-- ボタン -->
          <div class="center">
            <%= link_to "キャンセル", user_url(@user), class: "btn btn-md btn-default" %>
            <%= f.submit "変更を送信する", class: "btn btn-md btn-primary" %>
          </div>
        <% end %>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/reports/notice_report.js.erb
$("#notice_report").html("<%= escape_javascript(render 'notice_report') %>");
$("#notice_report").modal("show");